title: Welcome to my Tech Blog
description: A true believer of open Internet, this blog is my attempt at giving back to the great open source community.
show_downloads: false
google_analytics:
theme:
